### PR TITLE
Fix horizontal drag on stories scrolls tabs instead of stories

### LINKED ISSUE #31: [BUG] Cant scroll the users story on top of the screen
I cannot seem to scroll through the users stories on top of the screen, instead it shifts the tabs. If I view a story, and update, it does not move back into line either(however this might be on purpose) 

Edit: this has been moved to a seperate issue as per devs request. #35 
I̶t̶ ̶w̶o̶u̶l̶d̶ ̶a̶l̶s̶o̶ ̶b̶e̶ ̶n̶i̶c̶e̶ ̶i̶f̶ ̶t̶h̶e̶ ̶s̶t̶o̶r̶i̶e̶s̶ ̶t̶a̶b̶ ̶w̶o̶u̶l̶d̶ ̶d̶i̶s̶a̶p̶p̶e̶a̶r̶ ̶w̶h̶e̶n̶ ̶s̶c̶r̶o̶l̶l̶i̶n̶g̶ ̶d̶o̶w̶n̶w̶a̶r̶d̶s̶,̶ ̶o̶r̶ ̶a̶t̶l̶e̶a̶s̶t̶ ̶m̶a̶k̶e̶ ̶a̶n̶ ̶o̶p̶t̶i̶o̶n̶ ̶f̶o̶r̶ ̶i̶t̶,̶ ̶i̶f̶ ̶p̶e̶o̶p̶l̶e̶ ̶e̶n̶j̶o̶y̶ ̶h̶a̶v̶i̶n̶g̶ ̶i̶t̶ ̶t̶h̶e̶r̶e̶ ̶a̶l̶l̶ ̶t̶h̶e̶ ̶t̶i̶m̶e̶.̶ ̶ ̶I̶ ̶c̶a̶n̶ ̶m̶a̶k̶e̶ ̶t̶h̶i̶s̶ ̶i̶n̶t̶o̶ ̶a̶ ̶n̶e̶w̶ ̶i̶s̶s̶u̶e̶ ̶t̶o̶ ̶s̶e̶p̶a̶r̶a̶t̶e̶ ̶t̶h̶e̶m̶ ̶i̶f̶ ̶d̶e̶v̶ ̶w̶a̶n̶t̶ ̶t̶o̶.̶

### PR DESCRIPTION
**Pull request by ammargitham**
Fixes #31, at-least the scrolling part. Not sure about the "If I view a story, and update, it does not move back into line either(however this might be on purpose)", maybe create a new ticket for it with more details?

### CODE REVIEW

**Comment by austinhuang0131** [comment]
"If I scroll the list to somewhere, then refresh, the list doesn't scroll back to the place I left before"

@hovercats yeah that one is not really functionally possible because the app clears the story list on refresh and it is not guaranteed that stories will be shown in the same order

**Comment by austinhuang0131** [comment]
@ammargitham I'll leave it to you about considering whether the app should scroll back to where the user left off.

The "mark as seen" setting can be fetched through `settingsHelper.getBoolean(Constants.MARK_AS_SEEN)`.

**Comment by hovercats** [comment]
"If I view a story, and update, it does not move back into line either(however this might be on purpose)" just to clarify what I wrote. 
When I view a story, it should be marked as seen, as you said, and thus either be cleared from the list, or (as its on official app or webapp) its marked as seen, and promptly pushed the furthest back in the list of stories. The list is set up in chronological order, always newest first (or atleast thats how its supposed to be, but I assume theres some function that rather shows you those you view more often, but this is somewhat irrelevant in this matter).
Now, if I view 'bobs' story on instagrabber, and exits the app, and reopens the app (thus also refreshing) 'Bobs' story is still at the top, and not cleared as it should (or pushed furthest back in line as I said) 
Im sorry if my post was subject to misunderstanding, but I hope this helps to clarify the issue at hand.

**Comment by austinhuang0131** [comment]
@hovercats The app itself does not store what stories you've read as only knows whether or not a story has been read through Instagram. The app also does not manipulate the order of stories as we use them as-is from Instagram.

Starting v17.4, you can enable "mark stories as seen" in Settings. That way, the stories you've read will be pushed backward with a 50% transparent avatar. However, the ultimate consequence is that the users will know you read the story which is a privacy concern, so the option is default off

**Comment by hovercats** [comment]
Thank you for clearifying.

**Comment by austinhuang0131** [comment]
Alright, I think this PR solves the issue intended to be raised and I'll merge. If there are more questions, ask away (even after merge). @ammargitham Thank you for your continuous contribution!

**Pull request merged**
