### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by austinhuang0131**

### CODE REVIEW

**Comment by austinhuang0131** [comment]
@peterge1998 @MoaufmKlo consider checking the German translations, someone else joined the project recently and said

> "I have noticed that some strings are badly translated and/or missing. Especially the imperative in the settings. I want to create more clarity in the translation."

**Comment by MoaufmKlo** [comment]
That would work if you want, though only give us permissions for the German translations. I'll look into the translations asap (unless I forget).

**Comment by peterge1998** [comment]
Will look into crowdin this evening if not already done :)
Is there a way to flag strings as "could be improved" for the impertive ones?

**Comment by austinhuang0131** [comment]
@peterge1998 You can use comments. On translator view, it's on the right.

Anyways, @MoaufmKlo @peterge1998 @synarvis plus the new guy should now have proofreader permission for German now

**Pull request merged**
